### ISSUE TITLE
注入成功没有弹窗出现

### ISSUE THREAD

**Issue by jingshne** [snlie/WeChat-Hook#10]
最新的版，3。7。6。44，用C++的版本，获取个人信息，偏移量也已经改过了，注入提示成功，但没有弹窗，不知是何问题。

**Comment by ysn2382617094wsw** [comment]
dll可否发一下？

**Comment by jingshne** [comment]
> dll可否发一下？

问题已经解决了，感谢！不是dll的问题，是x86 /x64的问题

**Comment by lixh00** [comment]
> > dll可否发一下？
> 
> 问题已经解决了，感谢！不是dll的问题，是x86 /x64的问题

hello~

**Comment by xiongzhenglong** [comment]
msimg32.dll 可否分享下

**Comment by ysn2382617094wsw** [comment]
dll收钱的....
